apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata: 
    name: mycluster
    region: ap-south-1

nodeGroups:
     -  name: nodegroup1 
        instanceType: t2.micro
        desiredCapacity: 2
        ssh:
            publicKeyName: mykey1
     -  name: nodegroup2 
        instanceType: t2.small
        desiredCapacity: 1
        ssh:
            publicKeyName: mykey1

