apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mywebvol
    labels:
        server: apache_php

spec:
    accessModes:
     -  ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
